# Configuracion tempral
AGNO_INICIAL = 2022
AGNO_FINAL = 2041
MESES = 12

# Deficion Nombres en Hojas Modelos

NOMBRE_HOJA_MODELOS_ESCOGIDOS = 'Configuracion'
NOMBRE_HOJA_DETALLE_MODELOS_ESCOGIDOS = 'DetalleModelos'
PREFIJO_EFECTOS_FIJOS = 'EF'
PREFIJO_COEFICIENTES_VARIABLES = 'Var'
PREFIJO_COEFICIENTES_VARIABLES_CUADRADO = 'Var2'
